//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLocationServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coord
    {
        public int Id { get; set; }
        public double Lattitude { get; set; }
        public double Longitude { get; set; }
        public System.DateTime Time { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
